import OpenAI from 'openai';
import { AnalysisResult } from './analyzer';
import { withFallback } from '../utils/errorHandler';

// Initialize the OpenAI client for NVIDIA NIM
const ai = new OpenAI({
  baseURL: 'https://integrate.api.nvidia.com/v1',
  apiKey: process.env.NVIDIA_API_KEY
});

export interface ValidationResult {
  isValid: boolean;
  feedback: string;
}

const CRITIC_PROMPT = `
You are an Elite AI Systems Architect acting as 'The Critic/Validator' (Agent B).
Your job is to act as a 'Quality Gate' for a Candidate-Job Compatibility Engine.

You will be given:
1. The Job Description
2. The Candidate's Portfolio Context (9 years of Product Design history)
3. The Draft Analysis generated by Agent A (The Analyzer)

Your task:
Review Agent A's output. Ensure it is NOT generic, repetitive, or lacking specific evidence.
It MUST explicitly mention specific projects, skills, or business problems solved from the Portfolio Context
that directly map to the Job Description's requirements.

Output a valid JSON object with the exact following schema and nothing else:
{
  "isValid": boolean (true if the draft is highly specific and excellent, false if generic),
  "feedback": "string (specific instructions on what Agent A missed and must include, or 'Approved')"
}
`;

export async function validateAnalysis(jdText: string, portfolioContext: string, draft: AnalysisResult): Promise<ValidationResult> {
  const prompt = `
### Job Description
${jdText}

### Portfolio Context (9-year Product Design History)
${portfolioContext}

### Draft Analysis by Agent A
${JSON.stringify(draft, null, 2)}

Evaluate the Draft Analysis.
`;

  const primaryFn = async () => {
    const response = await ai.chat.completions.create({
      model: 'minimaxai/minimax-m2.7',
      messages: [
        { role: 'system', content: CRITIC_PROMPT },
        { role: 'user', content: prompt }
      ],
      temperature: 0.2,
      max_tokens: 4096,
    });

    const text = response.choices[0]?.message?.content;
    if (!text) {
      throw new Error("Critic returned empty response.");
    }

    // Strip markdown formatting if the model wraps it in \`\`\`json
    const cleanedText = text.replace(/^\`\`\`json/m, '').replace(/^\`\`\`/m, '').trim();

    return JSON.parse(cleanedText) as ValidationResult;
  };

  const secondaryFn = async () => {
    return { isValid: true, feedback: "Approved by fallback provider" };
  };

  return withFallback(primaryFn, secondaryFn, 'Agent B: Critic');
}
