import OpenAI from 'openai';
import { GoogleGenAI } from '@google/genai';
import { AnalysisResult } from './analyzer';
import { withFallback } from '../utils/errorHandler';

const ai = new OpenAI({
  baseURL: 'https://api.groq.com/openai/v1',
  apiKey: process.env.GROQ_API_KEY || 'dummy_key_for_build',
});

export interface ValidationResult {
  isValid: boolean;
  feedback: string;
}

const CRITIC_PROMPT = `
You are an Elite AI Systems Architect acting as 'The Critic/Validator' (Agent B).
Your job is to act as a 'Quality Gate' for a Candidate-Job Compatibility Engine.

You will be given:
1. The Job Description
2. The Candidate's Portfolio Context (9 years of Product Design history)
3. The Draft Analysis generated by Agent A (The Analyzer)

Your task:
Review Agent A's output. Ensure it is NOT generic, repetitive, or lacking specific evidence.
It MUST explicitly mention specific projects, skills, or business problems solved from the Portfolio Context
that directly map to the Job Description's requirements.

Output a valid JSON object with the exact following schema and nothing else:
{
  "isValid": boolean (true if the draft is highly specific and excellent, false if generic),
  "feedback": "string (specific instructions on what Agent A missed and must include, or 'Approved')"
}
`;

function extractJSON(text: string): string {
  const match = text.match(/\{[\s\S]*\}/);
  if (match) return match[0];
  return text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
}

function validateResult(parsed: unknown): ValidationResult {
  if (
    typeof parsed !== 'object' || parsed === null ||
    typeof (parsed as any).isValid !== 'boolean' ||
    typeof (parsed as any).feedback !== 'string'
  ) {
    throw new Error('Critic returned malformed JSON structure.');
  }
  const p = parsed as any;
  return { isValid: p.isValid, feedback: String(p.feedback).trim() };
}

export async function validateAnalysis(jdText: string, portfolioContext: string, draft: AnalysisResult): Promise<ValidationResult> {
  const prompt = `
### Job Description
${jdText}

### Portfolio Context (9-year Product Design History)
${portfolioContext}

### Draft Analysis by Agent A
${JSON.stringify(draft, null, 2)}

Evaluate the Draft Analysis.
`;

  const primaryFn = async () => {
    const response = await ai.chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: CRITIC_PROMPT },
        { role: 'user', content: prompt }
      ],
      temperature: 0.2,
      max_tokens: 256,
    });

    const text = response.choices[0]?.message?.content;
    if (!text) throw new Error('Critic returned empty response.');

    return validateResult(JSON.parse(extractJSON(text)));
  };

  const secondaryFn = async (): Promise<ValidationResult> => {
    console.warn('[Agent B] Critic primary provider failed. Switching to Gemini fallback...');
    try {
      const geminiApiKey = process.env.GEMINI_API_KEY;
      if (!geminiApiKey) throw new Error('GEMINI_API_KEY not found in environment.');
      
      const geminiAi = new GoogleGenAI({ apiKey: geminiApiKey });
      const response = await geminiAi.models.generateContent({
        model: 'gemini-2.5-pro',
        contents: [
          { role: 'user', parts: [{ text: CRITIC_PROMPT + '\n\n' + prompt }] }
        ],
        config: {
          temperature: 0.2,
          maxOutputTokens: 256,
        }
      });
      
      const text = response.text;
      if (!text) throw new Error('Gemini returned empty response.');
      return validateResult(JSON.parse(extractJSON(text)));
    } catch (e) {
      console.warn('[Agent B] Critic fallback also failed. Auto-approving draft.');
      return { isValid: true, feedback: 'Critic unavailable — proceeding with unvalidated draft.' };
    }
  };

  return withFallback(primaryFn, secondaryFn, 'Agent B: Critic');
}

